#!/usr/bin/env bash                                                                                                                                                     
createdb -E UTF8 template_postgis # Create the template spatial database.                                                                                               
createlang -d template_postgis plpgsql # Adding PLPGSQL language support.                                                                                               
psql -d template_postgis -f `pg_config --sharedir`/lwpostgis.sql # Loading the PostGIS SQL routines                                                                     
psql -d template_postgis -f `pg_config --sharedir`/spatial_ref_sys.sql
psql -d template_postgis -c "GRANT ALL ON geometry_columns TO PUBLIC;" # Enabling users to alter spatial tables.                                                        
psql -d template_postgis -c "GRANT ALL ON spatial_ref_sys TO PUBLIC;"


echo -n "Pick a database name: "
read -e DBNAME

createdb -U postgres -T template_postgis $DBNAME

echo -n "Pick a username: "
read -e USERNAME

echo -n "Pick a password: "
read -e PASSWORD

psql -c "create user $USERNAME with password '$PASSWORD';" $DBNAME
psql -c "grant all privileges on database $DBNAME to $USERNAME;" $DBNAME
echo "DATABASE_NAME = '$DBNAME'" >> local_settings.py
echo "DATABASE_USER = '$USERNAME'" >> local_settings.py
echo "DATABASE_PASSWORD = '$PASSWORD'" >> local_settings.py

