spanish={
'To open these data in another program, copy the text below into a text editor. Then save it with the ending".csv". This file can now be openes with Open Office and similar programs.':'Para usar estos datos en otros programas, copia el texto abajo a un editor de archivos de texto. Guardalo como un archivo del tipo ".csv". Este archivo se puede abrir en Open Office y otros programas parecidos.',
'Export data':'Exportar datos',
'To share this link, email':'Para compatir este gráfico, manda',
'this link':'este enlace',
'Permanent link':'Enlace permanente',
'Code to include in the wiki:':'Codigo para incluir en pagina de wiki:',
'Code for the wiki':'Codigo para la wiki',
'in':'en',
'day':'dia',
'month':'mes',
'year':'ano',
'median':'mediano',
'product':'producto',
'Edit Comment':'Editar Comentario',
'New Comment':'Nuevo Comentario',
'close':'cerrar',
'view':'ver',
'wiki code':'codigo wiki',
'link':'enlace',
'tables':'tablas',
'export':'exportar',
'Real':'Real',
'Normalized':'Normalizado',
'Comments':'Comentarios',
'product':'producto',
'market':'mercado',
'rain water station':'estacion de lluvia',
'date':'fecha',
'value':'valor',
'unit':'unidad',
'type':'tipo',
'Jan':'Ene',
'Feb':'Fev',
'Apr':'Abr',
'Dec':'Dic',
'all':'todos'
};