i18n={
//graph_drawer.js
'To open these data in another program, copy the text below into a text editor. Then save it with the ending".csv". This file can now be openes with Open Office and similar programs.':'Para usar estos datos en otros programas, copia el texto abajo a un editor de archivos de texto. Guardalo como un archivo del tipo ".csv". Este archivo se puede abrir en Open Office y otros programas parecidos.',
'Export data':'Exportar datos',
'To share this link, email':'Para compartir este gráfico, manda',
'this link':'este enlace',
'Permanent link':'Enlace permanente',
'Code to include in the wiki:':'Codigo para incluir en pagina de wiki:',
'Code for the wiki':'Codigo para la wiki',
'in':'en',
'day':'dia',
'month':'mes',
'year':'ano',
'daily':'diario',
'monthly':'mensual',
'annualy':'anual',
'median':'mediano',
'product':'producto',
'Edit Comment':'Editar Comentario',
'New Comment':'Nuevo Comentario',
'close':'cerrar',
'view':'ver',
'wiki code':'codigo wiki',
'link':'enlace',
'tables':'tablas',
'export':'exportar',
'Real':'Real',
'Normalized':'Normalizado',
'Comments':'Comentarios',
'product':'producto',
'market':'mercado',
'rain water station':'estacion de lluvia',
'date':'fecha',
'value':'valor',
'unit':'unidad',
'type':'tipo',
'Jan':'Ene',
'Feb':'Fev',
'Apr':'Abr',
'Aug':'Ago',
'Dec':'Dic',
'all':'todos',
'estimated value':'valor estimado',
'median of all markets and all products':'mediano de todos los mercados y todos los productos',
'New graph generated!':'Nuevo gráfico generado!',
'There is no data available for the selection!':'No hay datos para la seleccion!',
'We encountered an error!':'Hubo un error!',
// statistics_form.js
'Sunday':'Domingo',
'Monday':'Lunes',
'Tuesday':'Martes',
'Wednesday':'Miercoles',
'Thursday':'Jueves',
'Friday':'Viernes',
'Saturday':'Sabado',
'Sun':'Dom',
'Mon':'Lun',
'Tue':'Mar',
'Wed':'Mie',
'Thu':'Jue',
'Fri':'Vie',
'Sat':'Sab',
'Su':'Do',
'Mo':'Lu',
'Tu':'Ma',
'We':'Mi',
'Th':'Ju',
'Fr':'Vi',
'January':'Enero',
'February':'Febrero',
'March':'Marzo',
'April':'Abril',
'May':'Mayo',
'June':'Junio',
'July':'Julio',
'August':'Agosto',
'September':'Septiembre',
'October':'Octubre',
'November':'Noviembre',
'December':'Diciembre',
'Ja':'En',
'Ap':'Ab',
'Au':'Ag',
'De':'Di',
'We are experiencing network errors!':'Hay problemas con el red!',
'Please check the form!':'Por favor compruebe el formulario!',
'Ajax error: no data received.':'Eror de Ajax: ningunos datos recibido.',
// jquery.badBrowser.js
'ALBAstryde is a powerful application that requires a modern and professional browser. Unfortunately your current browser does not seem to fulfill the minimum criteria. However, there are many free ones that do, available on the internet. Please switch to':
'ALBAstryde es un programa muy poderoso que requiere un navegador moderno y profesional. Su navegador actual no cumple con los requisitos mínimos. Hay muchos otros navegadores que cumplen todos los requisitos en el Internet. Por favor, descarge',
'Thanks':'Gracias',
'or':'o',
};
